In [5]:
import pandas as pd

In [8]:
df = pd.read_sql("SELECT * FROM transport_libraries_view WHERE name = 'GRI-Mech'", "sqlite:///data/rmgdatabase/transport/transport.db").set_index("id")
df

,name,short_description,long_description,label,adjacency_list,shapeIndex,epsilon,epsilon_unit,sigma,sigma_unit,dipoleMoment,dipoleMoment_unit,polarizability,polarizability_unit,rotrelaxcollnum
id,,,,,,,,,,,,,,,
0,GRI-Mech,GRI-Mech3.0 value for AR,,AR,\n1 Ar u0 p4 c0\n,0,1134.930,J/mol,3.330,angstroms,0.0,C*m,0.00,angstroms^3,0.0
1,GRI-Mech,GRI-Mech3.0 value for C,,C(T),\nmultiplicity 3\n1 C u2 p1 c0\n,0,593.655,J/mol,3.298,angstroms,0.0,C*m,0.00,angstroms^3,0.0
2,GRI-Mech,GRI-Mech3.0 value for C2,,C2,"\nmultiplicity 3\n1 C u1 p0 c0 {2,T}\n2 C u1 p...",1,810.913,J/mol,3.621,angstroms,0.0,C*m,1.76,angstroms^3,4.0
3,GRI-Mech,GRI-Mech3.0 value for C2O,\nSame value as C2O(S).\n,C2O(T),"\nmultiplicity 3\n1 C u2 p0 c0 {2,D}\n2 C u0 p...",1,1932.290,J/mol,3.828,angstroms,0.0,C*m,0.00,angstroms^3,1.0
4,GRI-Mech,GRI-Mech3.0 value for C2O,\nSame Value as C2O(T).\n,C2O(S),"\n1 C u0 p1 c0 {2,D}\n2 C u0 p0 c0 {1,D} {3,D}...",1,1932.290,J/mol,3.828,angstroms,0.0,C*m,0.00,angstroms^3,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,GRI-Mech,GRI-Mech3.0 value for NCNO,,NCNO,"\n1 N u0 p1 c0 {2,T}\n2 C u0 p0 c0 {1,T} {3,S}...",2,1932.290,J/mol,3.828,angstroms,0.0,C*m,0.00,angstroms^3,1.0
88,GRI-Mech,GRI-Mech3.0 value for NO2,,NO2,"\nmultiplicity 2\n1 N u1 p0 c+1 {2,S} {3,D}\n2...",2,1662.900,J/mol,3.500,angstroms,0.0,C*m,0.00,angstroms^3,1.0
89,GRI-Mech,GRI-Mech3.0 value for O,,O(T),\nmultiplicity 3\n1 O u2 p2 c0\n,0,665.160,J/mol,2.750,angstroms,0.0,C*m,0.00,angstroms^3,0.0
90,GRI-Mech,GRI-Mech3.0 value for O2,,O2,"\nmultiplicity 3\n1 O u1 p2 c0 {2,S}\n2 O u1 p...",1,892.977,J/mol,3.458,angstroms,0.0,C*m,1.60,angstroms^3,3.8
91,GRI-Mech,GRI-Mech3.0 value for OH,,OH,"\nmultiplicity 2\n1 O u1 p2 c0 {2,S}\n2 H u0 p...",1,665.160,J/mol,2.750,angstroms,0.0,C*m,0.00,angstroms^3,0.0

In [3]:
# select all adjanency lists and epsilons where the unit of epsilon is J/mol
query = """SELECT adjacency_list, epsilon
FROM transport_libraries_view
WHERE epsilon_unit = 'J/mol'"""
pd.read_sql(query, "sqlite:///data/rmgdatabase/transport/transport.db")

                                        adjacency_list   epsilon
0                                    \n1 Ar u0 p4 c0\n  1134.930
1                     \nmultiplicity 3\n1 C u2 p1 c0\n   593.655
2    \nmultiplicity 3\n1 C u1 p0 c0 {2,T}\n2 C u1 p...   810.913
3    \nmultiplicity 3\n1 C u2 p0 c0 {2,D}\n2 C u0 p...  1932.290
4    \n1 C u0 p1 c0 {2,D}\n2 C u0 p0 c0 {1,D} {3,D}...  1932.290
..                                                 ...       ...
203  \n1 S u0 p2 c0 {2,S} {3,S}\n2 H u0 p0 c0 {1,S}...  1837.500
204         \n1 N u0 p1 c0 {2,T}\n2 N u0 p1 c0 {1,T}\n   810.913
205                                   \n1 C u0 p2 c0\n   593.655
206         \n1 N u0 p2 c0 {2,S}\n2 H u0 p0 c0 {1,S}\n   665.160
207                   \nmultiplicity 2\n1 N u1 p2 c0\n   593.655

[208 rows x 2 columns]

In [4]:
# this can also be done in pandas using typical pandas syntax
df[df["epsilon_unit"] == "J/mol"][["adjacency_list", "epsilon"]]

                                        adjacency_list   epsilon
id
0                                    \n1 Ar u0 p4 c0\n  1134.930
1                     \nmultiplicity 3\n1 C u2 p1 c0\n   593.655
2    \nmultiplicity 3\n1 C u1 p0 c0 {2,T}\n2 C u1 p...   810.913
3    \nmultiplicity 3\n1 C u2 p0 c0 {2,D}\n2 C u0 p...  1932.290
4    \n1 C u0 p1 c0 {2,D}\n2 C u0 p0 c0 {1,D} {3,D}...  1932.290
..                                                 ...       ...
221  \n1 S u0 p2 c0 {2,S} {3,S}\n2 H u0 p0 c0 {1,S}...  1837.500
222         \n1 N u0 p1 c0 {2,T}\n2 N u0 p1 c0 {1,T}\n   810.913
223                                   \n1 C u0 p2 c0\n   593.655
224         \n1 N u0 p2 c0 {2,S}\n2 H u0 p0 c0 {1,S}\n   665.160
225                   \nmultiplicity 2\n1 N u1 p2 c0\n   593.655

[208 rows x 2 columns]

These datasets are now:
 - 1. machine learning ready
 - 2. FAIR (Findable, Accessible, Interoperable, and Reusable for both humans _and_ machines)

In [21]:
df = pd.read_sql("SELECT * FROM thermo_libraries_view", "sqlite:///data/rmgdatabase/thermo/thermo.db").set_index("id")

In [30]:
for i, sub_df in df.groupby("id"):
    print(sub_df[['adjacency_list', 'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'poly_Tmin',
       'poly_Tmax', 'poly_T_unit']])
    break

       adjacency_list   c1   c2   c3   c4   c5       c6     c7  poly_Tmin  \
id
0   \n1 Ar u0 p4 c0\n  2.5  0.0  0.0  0.0  0.0 -745.375  4.366      298.0
0   \n1 Ar u0 p4 c0\n  2.5  0.0  0.0  0.0  0.0 -745.375  4.366     1000.0

    poly_Tmax poly_T_unit
id
0      1000.0           K
0      5000.0           K

In [31]:
df[['adjacency_list', 'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'poly_Tmin',
       'poly_Tmax', 'poly_T_unit']].dropna()

,adjacency_list,c1,c2,c3,c4,c5,c6,c7,poly_Tmin,poly_Tmax,poly_T_unit
id,,,,,,,,,,,
0,\n1 Ar u0 p4 c0\n,2.50000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,-745.375,4.366000,298.0,1000.0,K
0,\n1 Ar u0 p4 c0\n,2.50000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,-745.375,4.366000,1000.0,5000.0,K
1,"\n1 N u0 p1 c0 {2,T}\n2 N u0 p1 c0 {1,T}\n",2.92664,0.001488,-5.684760e-07,1.009700e-10,-6.753350e-15,-922.798,5.980530,1000.0,5000.0,K
1,"\n1 N u0 p1 c0 {2,T}\n2 N u0 p1 c0 {1,T}\n",3.29868,0.001408,-3.963220e-06,5.641520e-09,-2.444850e-12,-1020.900,3.950370,298.0,1000.0,K
2,\n1 He u0 p1 c0\n,2.50000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,-745.375,0.928724,200.0,1000.0,K
...,...,...,...,...,...,...,...,...,...,...,...
5732,"\nmultiplicity 2\n1 C u0 p0 c0 {2,S} {3,D} {4,...",4.77535,0.014604,-6.781530e-06,1.552370e-09,-1.416040e-13,35437.900,0.302320,1000.0,3000.0,K
5733,"\n1 N u0 p1 c0 {2,S} {4,S} {5,S}\n2 C u0 p0 c0...",3.17952,0.001946,3.433300e-05,-4.648260e-08,1.872680e-11,-24058.000,9.947550,200.0,1000.0,K
5733,"\n1 N u0 p1 c0 {2,S} {4,S} {5,S}\n2 C u0 p0 c0...",4.93695,0.009608,-3.329350e-06,5.165980e-10,-2.992030e-14,-25091.000,-2.000780,1000.0,6000.0,K
5734,"\n1 C u0 p0 c0 {3,S} {4,S} {5,S} {6,S}\n2 C ...",1.22882,0.026043,-4.950780e-06,-6.749540e-09,3.277390e-12,-3768.130,18.483200,298.0,1000.0,K
5734,"\n1 C u0 p0 c0 {3,S} {4,S} {5,S} {6,S}\n2 C ...",2.13913,0.026864,-1.287630e-05,2.996630e-09,-2.747720e-13,-4173.320,12.975900,1000.0,3000.0,K

Prediction of these fit params analogous to the methods of Chung et al. https://pubs.acs.org/doi/abs/10.1021/acs.jcim.1c01103